### ISSUE TITLE
Single Piece Spool Holder 3030 Slide in T-Nut

### ISSUE THREAD

**Issue by brewpirate** [AdamV3D/RR-V-Minion-Mods#1]
Enjoying the spool holder but had one minor issue when using on my minion.  The model has a 15mm gap for the t-nut however my 3030 slide in t-nuts measure 15.5mm. Would it be possible to increase the spacing?

T-nuts purchased:

- https://www.amazon.com/gp/product/B07RGSW1J2?th=1
- https://www.amazon.com/gp/product/B07L111F2Z/

**Comment by AdamV3D** [comment]
Ah I see, you're using the pre-assembly ones as apposed to the hammer nut style for which they are intended. Yes should be ok to widen that by 1mm.

**Comment by AdamV3D** [comment]
The gap is increased from 15mm to 16mm to allow for slide-in T-nuts
